### ISSUE TITLE
undefined "global" variable

### ISSUE THREAD

**Issue by Christoph142** [inspect-js/typed-array-byte-offset#2]
This library got pulled in as a dependency into our Angular 16 project this week and it prevents our page from loading (Chromium 122), because it throws an error in https://github.com/inspect-js/typed-array-byte-offset/blob/10b0823ecc13b95920cfa8f27fe61af5678fb67b/index.js#L24C14-L24C20
global is not defined:
![image](https://github.com/inspect-js/typed-array-byte-offset/assets/1440823/ad14b14c-43db-4690-a1dc-06775eab8054)

**Comment by ljharb** [comment]
It’s always defined, since this is a node module. Are you using a broken bundler, perhaps?

**Comment by Christoph142** [comment]
Not sure how this happens exactly. A third party dependency got updated (npm update - node 18.19.1 which bundles npm 10.2.4) and this library got added as a dependency thereof. Npm resolved properly, npm start also builds the project successfully, but trying to open the resulting angular app only yields this console error and that's it. 🤔

**Comment by Christoph142** [comment]
A quick research hints to a rename of global into globalThis:
https://nodejs.org/api/globals.html#global

**Comment by Christoph142** [comment]
https://github.com/nodejs/node/issues/47784

**Comment by ljharb** [comment]
Seems like whatever ng build is using fails to transform global to either globalThis or window.

**Comment by Christoph142** [comment]
Yeah, seems like a previously existing shim has been removed deliberately: https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814

**Comment by ljharb** [comment]
Seems like that issue has workarounds for you.

**Comment by Christoph142** [comment]
![image](https://github.com/inspect-js/typed-array-byte-offset/assets/1440823/d8ce6f5e-1a16-46ed-a564-926d6e9f0191)
This is pretty clear, isn't it? This is node, not angular.

**Comment by ljharb** [comment]
I support node versions that don’t have globalThis.

The maintainer in that linked issue is simply wrong; this is a node module, and a working node module bundler transforms or shims `global`.
